### PR TITLE
Separate options for the module type prefix in IDs (anchors) and file names

### LINKED ISSUE #21: ID without a prefix by default
According to my recent survey, most people don't want the ID to have a module-type prefix. Let's change the default behavior.

However, the results were extremely close, so the feature must be easily configurable.

Finally, if we want to keep the default prefix in the file name, we need two options: one that configures the filename prefix, and one that configures the ID prefix.

### PR DESCRIPTION
**Pull request by msuchane**
Closes #21

### CODE REVIEW

**Comment by msuchane** [comment]
Hi @mjahoda and @Levi-Leah,

Could you please test a new version of newdoc? It splits the prefix configuration by file name and ID (anchor), and by default, it uses the prefix in the file name but not in the ID (anchor).

How to test:

1. Install the Rust toolchain at version 1.60 or later. Either install `cargo` from your distribution packages or use <https://rustup.rs/>.

2. Compile and install the testing version of newdoc:

    ```
    $ cargo install --git https://github.com/redhat-documentation/newdoc.git --branch no-id-prefixes-21
    ```

3. Generate files using `newdoc` and test the following options:

    * `--no-file-prefixes`: Disables the file-name prefix.
    * `--anchor-prefixes`: Enables the ID (anchor) prefix.

4. Uninstall the testing version of `newdoc`:

    ```
    $ cargo uninstall newdoc
    ```

Thanks for your help!

**Comment by mjahoda** [comment]
@msuchane Thank you for your great work. Just a nitpick to step 2 in the test instructions - there is a copy-paste error doubling the commands and the options.

All works as designed:
```$ newdoc -p "Testing defaults" -C
[INFO] ‣ File generated: ./proc_testing-defaults.adoc
[INFO]   include::<path>/proc_testing-defaults.adoc[leveloffset=+1]
$ newdoc -p "Testing no-prefixes" -C --no-file-prefixes
[INFO] ‣ File generated: ./testing-no-prefixes.adoc
[INFO]   include::<path>/testing-no-prefixes.adoc[leveloffset=+1]
$ newdoc -p "Testing anchor-prefixes" -C --anchor-prefixes
[INFO] ‣ File generated: ./proc_testing-anchor-prefixes.adoc
[INFO]   include::<path>/proc_testing-anchor-prefixes.adoc[leveloffset=+1]
$ grep "id=" *testing*.adoc
proc_testing-anchor-prefixes.adoc:[id="proc_testing-anchor-prefixes_{context}"]
proc_testing-defaults.adoc:[id="testing-defaults_{context}"]
testing-no-prefixes.adoc:[id="testing-no-prefixes_{context}"]```

**Review by mjahoda — APPROVED** [review]
As described in https://github.com/redhat-documentation/newdoc/pull/34#issuecomment-1279710271, I verified the changes.

**Comment by msuchane** [comment]
Thanks, @mjahoda! For your review and also for discovering the copy-paste typo. After all the programming was done, my copy-paste strength apparently left me :-D

**Review by Levi-Leah — COMMENTED** [review]
Works as expected. LGTM!

**Comment by msuchane** [comment]
Thanks for your reviews. I'm merging the branch and I'll release the new version in a moment.

**Pull request merged**
